version: 2
updates:
  package-ecosystem: "github-actions"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "npm"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "bundler"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "pip"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "maven"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "gradle"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "docker"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "cpp"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "shell"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "php"

directory: "/"
schedule:
interval: "weekly"
  package-ecosystem: "python"

directory: "/"
schedule:
interval: "weekly"
